---
title: SYSUSA Security Operations.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  cards:
    title: cards
    output: true
defaults:
- scope:
    path: ''
    type: cards
  values:
    image: 
    is-normal: true
email: viraj.chaudhary@apexure.com
description: 'website using html css bootstrap jekyll git and github and site leaf
  as CMS '
baseurl: "/Security_Operations"
url: https://virajchuaudhary.github.io
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
Header:
  logo: "/uploads/logo.svg"
  cta-button-text: 'SCHEDULE A CONSULTATION TODAY '
  cta-button-url: "#"
footer:
  copyright: 'Copyright © 2021 SYSUSA | All Rights Reserved '
  privacy-text: Privacy Policy
  privacy-url: "#Privacy Policy"
